# Generated by Django 6.0.8 on 2026-08-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_options_payment_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='correction_history',
            field=models.JSONField(blank=True, default=list, help_text='Audit trail of all correction requests'),
        ),
        migrations.AddField(
            model_name='payment',
            name='correction_notes',
            field=models.TextField(blank=True, default='', help_text='Latest correction request details from admin'),
        ),
    ]
