# Generated by Django 6.0.8 on 2026-08-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_initial'),
        ('elections', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='members.member'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'position', 'member')},
        ),
    ]
