# Generated by Django 6.0.8 on 2026-08-11 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_signature',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='contribution_to_org',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='personal_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CandidateEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsement_type', models.CharField(choices=[('proposer', 'Proposer'), ('supporter', 'Supporter')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('citizenship_number', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('membership_id', models.CharField(blank=True, default='', max_length=100)),
                ('signature_url', models.URLField(blank=True, default='')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidate_endorsements',
                'ordering': ['created_at'],
            },
        ),
    ]
