# Generated by Django 6.0.8 on 2026-08-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_unique_together_candidate_address_and_more'),
        ('elections', '0007_position_quotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='elections.positionquota'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='quota_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
