# Generated by Django 6.0.8 on 2026-08-16 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_position_quotas'),
        ('elections', '0008_election_allow_boycott'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateObjection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimant_name', models.CharField(max_length=255)),
                ('claimant_email', models.EmailField(max_length=255)),
                ('claimant_phone', models.CharField(blank=True, default='', max_length=50)),
                ('claimant_citizenship_number', models.CharField(blank=True, default='', max_length=100)),
                ('objection_reason', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='candidate_objections/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('upheld', 'Upheld (Objection Accepted)'), ('dismissed', 'Dismissed (Candidate Cleared)')], db_index=True, default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='candidates.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_objections', to='elections.election')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_candidate_objections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_objections',
                'ordering': ['-created_at'],
            },
        ),
    ]
