# Generated by Django 6.0.8 on 2026-08-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidateobjection'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid / Verified'), ('waived', 'Waived / Free')], db_index=True, default='unpaid', max_length=30),
        ),
    ]
