# Generated by Django 6.0.8 on 2026-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='panel_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pr_rank',
            field=models.PositiveIntegerField(default=1, help_text='Rank/Priority order on party PR closed list'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='symbol_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='symbol_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
