# Generated by Django 6.0.8 on 2026-08-05 06:25

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ballot_data', models.JSONField()),
                ('receipt_hash', models.CharField(max_length=64, unique=True)),
                ('weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.CreateModel(
            name='VoterRoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('ineligibility_reason', models.CharField(blank=True, default='', max_length=255)),
                ('has_voted', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('voted_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_roll', to='elections.election')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_rolls', to='members.member')),
            ],
            options={
                'db_table': 'voter_rolls',
            },
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter_roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to='voting.voterroll')),
            ],
            options={
                'db_table': 'voting_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='voterroll',
            index=models.Index(fields=['election', 'has_voted'], name='voter_rolls_electio_2625ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voterroll',
            unique_together={('election', 'member')},
        ),
    ]
