# Generated by Django 6.0.8 on 2026-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_voterroll_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterroll',
            name='voted_mac_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
