# Generated by Django 6.0.8 on 2026-08-16 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_election_allow_boycott'),
        ('voting', '0003_voterroll_voted_mac_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(choices=[('omission', 'Omission (Missing Name in Voter Roll)'), ('correction', 'Correction (Wrong Name/Details in Voter Roll)'), ('objection', 'Objection (Ineligible Voter in Voter Roll)')], default='omission', max_length=20)),
                ('claimant_name', models.CharField(max_length=255)),
                ('claimant_email', models.EmailField(max_length=255)),
                ('claimant_phone', models.CharField(blank=True, default='', max_length=50)),
                ('claimant_citizenship_number', models.CharField(blank=True, default='', max_length=100)),
                ('target_voter_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='voter_claims/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_claims', to='elections.election')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_voter_claims', to=settings.AUTH_USER_MODEL)),
                ('voter_roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='voting.voterroll')),
            ],
            options={
                'db_table': 'voter_claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
