# Generated by Django 6.0.8 on 2026-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voterclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterroll',
            name='direct_ballot_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='voterroll',
            name='direct_ballot_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterroll',
            name='direct_ballot_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterroll',
            name='verification_channel',
            field=models.CharField(choices=[('unverified', 'Pending Verification'), ('mobile_app', 'Verified via Mobile App'), ('web_email', 'Verified via Web / Email'), ('venue_kiosk', 'Verified at Venue Kiosk')], default='unverified', help_text='Channel through which the voter verified identity', max_length=20),
        ),
        migrations.AddField(
            model_name='voterroll',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
