# Generated by Django 6.0.8 on 2026-09-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_election_election_method_election_online_type_and_more'),
        ('voting', '0005_voterroll_direct_ballot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterroll',
            name='voter_pin',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique collision-free PIN for polling station booth check-in', max_length=32),
        ),
        migrations.AddIndex(
            model_name='voterroll',
            index=models.Index(fields=['election', 'voter_pin'], name='voter_rolls_electio_225947_idx'),
        ),
    ]
