# Generated by Django 6.0.8 on 2026-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_voterroll_voter_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterroll',
            name='branch',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Branch/Chapter of the voter (e.g. Kathmandu Branch, Chitwan Branch)', max_length=100),
        ),
    ]
