# Generated by Django 6.0.8 on 2026-08-05 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('nomination_open', 'Nomination Open'), ('nomination_closed', 'Nomination Closed'), ('voting_open', 'Voting Open'), ('voting_closed', 'Voting Closed'), ('results_provisional', 'Results Provisional'), ('results_final', 'Results Final'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('voter_roll_freeze_date', models.DateField(blank=True, null=True)),
                ('voter_roll_frozen_at', models.DateTimeField(blank=True, null=True)),
                ('nomination_open_at', models.DateTimeField(blank=True, null=True)),
                ('nomination_close_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_deadline', models.DateTimeField(blank=True, null=True)),
                ('campaign_silent_from', models.DateTimeField(blank=True, null=True)),
                ('voting_start_at', models.DateTimeField(blank=True, null=True)),
                ('voting_end_at', models.DateTimeField(blank=True, null=True)),
                ('result_contest_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_secret_ballot', models.BooleanField(default=True)),
                ('results_visibility', models.CharField(choices=[('admin_only', 'Admin Only'), ('org_members', 'Organization Members'), ('public', 'Public')], default='admin_only', max_length=20)),
                ('live_turnout_enabled', models.BooleanField(default=True)),
                ('resubmission_allowed', models.BooleanField(default=False, help_text='Allow rejected candidates to resubmit (doc: 14-Candidate-Management.md §14.3)')),
                ('ballot_snapshot_hash', models.CharField(blank=True, default='', help_text='SHA-256 of locked candidate list at voting-open time (doc: 16-Ballot-Builder.md §16.7)', max_length=64)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='organizations.organization')),
            ],
            options={
                'db_table': 'elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectionStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('nomination_open', 'Nomination Open'), ('nomination_closed', 'Nomination Closed'), ('voting_open', 'Voting Open'), ('voting_closed', 'Voting Closed'), ('results_provisional', 'Results Provisional'), ('results_final', 'Results Final'), ('cancelled', 'Cancelled')], max_length=30)),
                ('to_state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('nomination_open', 'Nomination Open'), ('nomination_closed', 'Nomination Closed'), ('voting_open', 'Voting Open'), ('voting_closed', 'Voting Closed'), ('results_provisional', 'Results Provisional'), ('results_final', 'Results Final'), ('cancelled', 'Cancelled')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='elections.election')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null = system-triggered (Celery)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'election_state_transitions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('seats_available', models.PositiveIntegerField(default=1)),
                ('voting_method', models.CharField(choices=[('fptp', 'First-Past-The-Post'), ('multi_choice', 'Multiple Choice (Block)'), ('ranked_choice', 'Ranked Choice (STV)'), ('approval', 'Approval Voting'), ('weighted', 'Weighted Voting'), ('proxy', 'Proxy Voting'), ('yes_no', 'Yes/No (Referendum)')], default='fptp', max_length=20)),
                ('max_votes_per_voter', models.PositiveIntegerField(default=1, help_text='Relevant for multi_choice — how many candidates voter can pick')),
                ('eligibility_rule', models.JSONField(blank=True, default=dict, help_text='e.g. {"membership_status": "active", "min_membership_months": 12}')),
                ('ballot_ordering', models.CharField(choices=[('alphabetical', 'Alphabetical'), ('random', 'Random'), ('manual', 'Manual')], default='random', max_length=20)),
                ('super_majority_threshold', models.FloatField(blank=True, help_text='e.g. 0.667 for 66.7% threshold (doc: 15-Voting-Engine.md §15.6)', null=True)),
                ('abstain_allowed', models.BooleanField(default=False)),
                ('none_of_the_above', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectionRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('election_officer', 'Election Officer'), ('observer', 'Observer'), ('auditor', 'Auditor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'election_role_assignments',
                'unique_together': {('user', 'election', 'role')},
            },
        ),
    ]
