# Generated by Django 6.0.8 on 2026-08-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='candidacy_claim_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='candidacy_final_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='election',
            name='final_voter_list_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='first_voter_list_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='is_paid_candidacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='election',
            name='nominee_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='election',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='election',
            name='primary_color',
            field=models.CharField(blank=True, default='#6C5CE7', max_length=7),
        ),
        migrations.AddField(
            model_name='election',
            name='secondary_color',
            field=models.CharField(blank=True, default='#A29BFE', max_length=7),
        ),
        migrations.AddField(
            model_name='election',
            name='voter_list_claim_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
