# Generated by Django 6.0.8 on 2026-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_add_branding_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='bg_color',
            field=models.CharField(blank=True, default='#563d7c', max_length=7),
        ),
        migrations.AddField(
            model_name='position',
            name='nominee_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='position',
            name='quota_name',
            field=models.CharField(blank=True, default='', help_text='e.g., Dalit, Female, Open', max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='result_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first in results'),
        ),
    ]
