# Generated by Django 6.0.8 on 2026-08-12 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_position_bg_color_position_nominee_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='guidelines',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ElectionNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='elections.election')),
            ],
            options={
                'db_table': 'election_notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
