# Generated by Django 6.0.8 on 2026-08-13 04:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_election_guidelines_electionnotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCommittee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee_type', models.CharField(choices=[('new', 'Create New Committee'), ('existing', 'Select Existing Committee')], default='new', max_length=20)),
                ('committee_name', models.CharField(max_length=255)),
                ('chair_designation', models.CharField(blank=True, default='', max_length=255)),
                ('chair_contact', models.CharField(blank=True, default='', max_length=100)),
                ('chair_email', models.EmailField(max_length=254)),
                ('chair_signature', models.ImageField(blank=True, null=True, upload_to='committee_signatures/')),
                ('chair_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committees', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='elections.election')),
            ],
            options={
                'db_table': 'election_committees',
                'ordering': ['-created_at'],
            },
        ),
    ]
