# Generated by Django 6.0.8 on 2026-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_election_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncommittee',
            name='role',
            field=models.CharField(choices=[('election_officer', 'Election Officer'), ('observer', 'Observer'), ('auditor', 'Auditor')], default='election_officer', max_length=50),
        ),
    ]
