# Generated by Django 6.0.8 on 2026-08-14 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_add_role_to_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Female, Dalit, Janajati, Youth, Open', max_length=100)),
                ('seats', models.PositiveIntegerField(default=1, help_text='Number of reserved seats')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='elections.position')),
            ],
            options={
                'db_table': 'position_quotas',
                'ordering': ['created_at'],
            },
        ),
    ]
