# Generated by Django 6.0.8 on 2026-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_position_quotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='allow_boycott',
            field=models.BooleanField(default=True, help_text='Allow voters to choose No Vote / Boycott (बहिष्कार)'),
        ),
    ]
