# Generated by Django 6.0.8 on 2026-08-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_election_allow_boycott'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='election_stamps/'),
        ),
        migrations.AddField(
            model_name='election',
            name='stamp_mode',
            field=models.CharField(choices=[('digital', 'Digital Stamp'), ('manual', 'Manual Wet Stamp')], default='digital', max_length=20),
        ),
        migrations.AddField(
            model_name='electioncommittee',
            name='include_in_letterhead',
            field=models.BooleanField(default=True, help_text='Whether this committee member appears in the official letterhead signature block.'),
        ),
        migrations.AddField(
            model_name='electionnotice',
            name='notice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='electionnotice',
            name='stamp_mode',
            field=models.CharField(choices=[('digital', 'Digital Stamp'), ('manual', 'Manual Wet Stamp')], default='digital', max_length=20),
        ),
    ]
