# Generated by Django 6.0.8 on 2026-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_election_show_uncontested_in_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_method',
            field=models.CharField(choices=[('online', 'Method 1: Online / Remote Voting'), ('venue', 'Method 2: Venue / Device-Based Voting')], default='online', help_text='Method 1: Online/Remote vs Method 2: Venue/Device-Based', max_length=20),
        ),
        migrations.AddField(
            model_name='election',
            name='online_type',
            field=models.CharField(choices=[('mobile_app', 'Type 1: Mobile App Based'), ('web_based', 'Type 2: Web Based (Email OTP + Ballot Link)'), ('hybrid', 'Type 3: Hybrid (Both Mobile & Web)')], default='hybrid', help_text='Type 1: Mobile App, Type 2: Web Based, Type 3: Hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='election',
            name='require_venue_otp',
            field=models.BooleanField(default=False, help_text='Require SMS OTP or email confirmation at venue booth (Method 2 optional layer)'),
        ),
        migrations.AddField(
            model_name='election',
            name='venue_address',
            field=models.TextField(blank=True, default='', help_text='Full physical address for Method 2 elections'),
        ),
        migrations.AddField(
            model_name='election',
            name='venue_name',
            field=models.CharField(blank=True, default='', help_text='Physical location name for Method 2 elections', max_length=255),
        ),
        migrations.AddField(
            model_name='election',
            name='venue_otp_channel',
            field=models.CharField(choices=[('none', 'None (Voter ID Only)'), ('sms', 'SMS OTP'), ('email', 'Email Confirmation Link'), ('both', 'Both SMS & Email')], default='none', help_text='Secondary verification channel for venue voting', max_length=20),
        ),
    ]
