# Generated by Django 6.0.8 on 2026-09-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_election_election_method_election_online_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('fptp', 'First-Past-The-Post (FPTP)'), ('samanupatik', 'Samānupātik (Proportional Representation)')], default='fptp', help_text='Voting system type: FPTP vs Samānupātik PR', max_length=30),
        ),
        migrations.AddField(
            model_name='election',
            name='enable_candidate_photo',
            field=models.BooleanField(default=True, help_text='Enable / Disable candidate photos on ballot'),
        ),
        migrations.AddField(
            model_name='election',
            name='enable_panel',
            field=models.BooleanField(default=True, help_text='Enable / Disable Panel affiliation for candidates & voting'),
        ),
        migrations.AddField(
            model_name='election',
            name='enable_party',
            field=models.BooleanField(default=True, help_text='Enable / Disable Party affiliation for candidates & voting'),
        ),
        migrations.AddField(
            model_name='election',
            name='enable_symbol',
            field=models.BooleanField(default=True, help_text='Enable / Disable election symbols on ballot'),
        ),
        migrations.AddField(
            model_name='election',
            name='is_partial_election',
            field=models.BooleanField(default=False, help_text='Partial Election for specific branches only'),
        ),
        migrations.AddField(
            model_name='election',
            name='pr_allocation_method',
            field=models.CharField(choices=[('sainte_lague', 'Sainte-Laguë Method'), ('dhondt', "d'Hondt Method"), ('hare_quota', 'Hare Quota (Largest Remainder)')], default='sainte_lague', help_text='Mathematical PR quota formula for seat allocation', max_length=30),
        ),
        migrations.AddField(
            model_name='election',
            name='pr_threshold_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum vote percentage threshold for PR seat allocation (e.g. 3.00%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='election',
            name='target_branches',
            field=models.JSONField(blank=True, default=list, help_text='List of branch names or IDs eligible for this partial election'),
        ),
        migrations.AddField(
            model_name='election',
            name='total_pr_seats',
            field=models.PositiveIntegerField(default=10, help_text='Total seats allocated for Samānupātik / PR election'),
        ),
    ]
