# Generated by Django 6.0.8 on 2026-09-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_election_election_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('fptp', 'First-Past-The-Post (FPTP)'), ('samanupatik', 'Samānupātik (Proportional Representation)'), ('mixed', 'Mixed / Parallel (मिश्रित - FPTP + Samānupātik)')], default='fptp', help_text='Voting system type: FPTP vs Samānupātik PR vs Mixed', max_length=30),
        ),
    ]
