# Generated by Django 6.0.8 on 2026-08-05 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('org_type', models.CharField(choices=[('cooperative', 'Cooperative / SACCO'), ('college', 'College / University'), ('association', 'Professional Association'), ('club', 'Club / Community'), ('housing_society', 'Housing Society'), ('union', 'Trade Union'), ('ngo', 'NGO / INGO'), ('corporate', 'Corporate'), ('religious', 'Religious Organization'), ('political_party', 'Political Party (Internal)'), ('other', 'Other')], default='other', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('default_language', models.CharField(choices=[('ne', 'Nepali'), ('en', 'English')], default='ne', max_length=5)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('brand_color', models.CharField(blank=True, default='#1976D2', max_length=7)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('grievance_window_days', models.PositiveIntegerField(default=3)),
                ('voter_roll_freeze_offset_days', models.IntegerField(default=0, help_text='Days before nomination-open date. 0 = freeze on nomination-open date.')),
                ('default_nomination_window_days', models.PositiveIntegerField(default=7)),
                ('default_voting_window_days', models.PositiveIntegerField(default=1)),
                ('default_silent_period_hours', models.PositiveIntegerField(default=24)),
                ('default_result_visibility', models.CharField(choices=[('admin_only', 'Admin Only'), ('org_members', 'Org Members'), ('public', 'Public')], default='admin_only', max_length=20)),
                ('election_officers_can_publish', models.BooleanField(default=False, help_text='If True, Election Officers can self-publish results (doc: 10-RBAC-Permissions.md)')),
                ('data_retention_years', models.PositiveIntegerField(default=7, help_text='Minimum 1 year enforced at platform level.')),
                ('legal_hold', models.BooleanField(default=False, help_text='Blocks automated retention-purge jobs (doc: 19-Audit-Compliance.md §19.7)')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='billing.subscriptionplan')),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
