# Generated by Django 6.0.8 on 2026-08-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_qr_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_swift_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='council_number',
            field=models.CharField(blank=True, default='', help_text='Registration / council number issued by the relevant authority', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text='Short prefix/abbreviation, e.g. SOC, NMB, HAN', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='type_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('cooperative', 'Cooperative / SACCO'), ('college', 'College / University'), ('association', 'Professional Association'), ('club', 'Club / Community'), ('housing_society', 'Housing Society'), ('union', 'Trade Union'), ('ngo', 'NGO / INGO'), ('corporate', 'Corporate'), ('religious', 'Religious Organization'), ('political_party', 'Political Party (Internal)'), ('government', 'Government / Public Body'), ('educational', 'Educational Institution'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
