# Generated by Django 6.0.8 on 2026-08-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_contact_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
