# Generated by Django 6.0.8 on 2026-08-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Payment gateway configuration. Structured JSON per gateway.'),
        ),
    ]
